### ISSUE TITLE
Missing Requirements and Config File

### ISSUE THREAD

**Issue by plicit** [jeffrimko/PyQuickWin#1]
Looks interesting!  I'd guess that the requirements.txt are:

```
auxly
ujson
pyyaml
wxpython
```

But then it still crashes because it is looking for a config file which is missing.

**Comment by jeffrimko** [comment]
Hi, thanks for taking a look! Yeah, I was hoping to have better docs written up by now but running a bit behind. It's still a work in progress although it is functional and I am using it daily. Please note that I use Windows and am not certain how well it will work on other operating systems. The most recent commit contains a bit more info in the README as well as an example config file. Hopefully that will get it working so you can try it out if you'd like.

**Comment by plicit** [comment]
That did it, looks good, thanks! :)
